const allReviews = [
  {
    name: 'Aarav Mehta',
    rating: 5,
    review: 'Absolutely loved the quality! Fits perfectly and delivery was quick.',
    date: '2025-05-01',
    avatar: 'https://i.pravatar.cc/150?img=11',
  },
  {
    name: 'Sneha Kapoor',
    rating: 4,
    review: 'Very stylish and comfortable. Would definitely buy again.',
    date: '2025-05-02',
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    name: 'Raj Malhotra',
    rating: 4,
    review: 'Product was good but the packaging could be improved.',
    date: '2025-05-03',
    avatar: 'https://i.pravatar.cc/150?img=13',
  },
  {
    name: 'Priya Singh',
    rating: 5,
    review: 'Exceeded expectations! Highly recommended.',
    date: '2025-05-04',
    avatar: 'https://i.pravatar.cc/150?img=14',
  },
  {
    name: 'Kabir Sharma',
    rating: 5,
    review: 'Excellent material and true to size.',
    date: '2025-05-05',
    avatar: 'https://i.pravatar.cc/150?img=15',
  },
  {
    name: 'Ananya Desai',
    rating: 5,
    review: 'Super fast delivery and awesome fit. Loved it!',
    date: '2025-05-06',
    avatar: 'https://i.pravatar.cc/150?img=16',
  },
  {
    name: 'Rohan Patel',
    rating: 3,
    review: 'Looks good, but size was slightly off for me.',
    date: '2025-05-07',
    avatar: 'https://i.pravatar.cc/150?img=17',
  },
  {
    name: 'Isha Nair',
    rating: 4,
    review: 'Perfect for casual wear. Fabric is really soft.',
    date: '2025-05-08',
    avatar: 'https://i.pravatar.cc/150?img=18',
  },
  {
    name: 'Vikram Joshi',
    rating: 5,
    review: 'Loved the style and fitting. Great value for money.',
    date: '2025-05-09',
    avatar: 'https://i.pravatar.cc/150?img=19',
  },
  {
    name: 'Meera Iyer',
    rating: 4,
    review: 'The color is vibrant and the design is unique.',
    date: '2025-05-10',
    avatar: 'https://i.pravatar.cc/150?img=20',
  },
  {
    name: 'Yash Thakur',
    rating: 5,
    review: 'This was my second purchase. Totally worth it.',
    date: '2025-05-11',
    avatar: 'https://i.pravatar.cc/150?img=21',
  },
  {
    name: 'Ritika Shah',
    rating: 4,
    review: 'Looks good with both jeans and shorts. Go for it.',
    date: '2025-05-12',
    avatar: 'https://i.pravatar.cc/150?img=22',
  },
  {
    name: 'Ayaan Qureshi',
    rating: 3,
    review: 'Nice but the delivery got delayed by 2 days.',
    date: '2025-05-13',
    avatar: 'https://i.pravatar.cc/150?img=23',
  },
  {
    name: 'Tanya Verma',
    rating: 5,
    review: 'Amazing product at this price. Great buy!',
    date: '2025-05-14',
    avatar: 'https://i.pravatar.cc/150?img=24',
  },
  {
    name: 'Dev Mishra',
    rating: 4,
    review: 'Material feels premium and it’s very breathable.',
    date: '2025-05-15',
    avatar: 'https://i.pravatar.cc/150?img=25',
  },
];
export default allReviews;